### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Moushudyx** [Moushudyx/foreslash#1]
- [x] Random: uuid(v4), ulid([spec](https://github.com/ulid/spec))
- [x] Async: tryit(error first), defer(go like), parallel(async funcs), retry(async funcs), sleep(ms)
    - tryit: `const [err, res] = tryit(asyncFunction)`
    - defer: `defer(async (d) => { d(willBeCalledAfterTheReturn); /* ... */; return xxx; })`
- [x] Functional: memorize(pure func), debounce, throttle
- [x] String: capitalize, caseXXX(camel, pascal, snake, kebab, title), splitWords(for caseXXX)
    - caseCamel: `caseCamel`
    - casePascal: `CasePascal`
    - caseSnake: `case_snake`
    - caseKebab: `case-kebab`
    - caseTitle: `Case Title`
    - splitWords: `splitWords`, `SplitWords`, `split words` → `['split', 'words']`
- [x] Array: remove(item from array)
    - remove: `remove([1, 2, NaN, 3], NaN) // [1, 2, 3]`
- [x] Object: clone(deep clone), merge(fast merge & deep merge)
- [x] misc: range(radash like)
    - range: `range(3) // [0, 1, 2, 3]`, `range(1, 7, 2) // [1, 3, 5, 7]`, `range(1, 7, 2, i => 'a' + i) // ['a1', 'a3', 'a5', 'a7']`
